### ISSUE TITLE
Wrong gref passed from front

### ISSUE THREAD

**Issue by andr2000** [al1img/displ_be#1]
16.12.16 15:48:47.712 | BuffersStorage | ERR - Gref addre: 0x7ffff7fee004

Thread 6 "displ_be" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef7fe700 (LWP 5000)]
__memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:238
238	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:238
#1  0x00000000004682cc in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned int> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0)
    at /usr/include/c++/5/bits/stl_algobase.h:384
#2  0x0000000000467d71 in std::__copy_move_a<false, unsigned int*, unsigned int*> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0) at /usr/include/c++/5/bits/stl_algobase.h:402
#3  0x00000000004685e7 in std::__copy_move_a2<false, unsigned int*, unsigned int*> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0) at /usr/include/c++/5/bits/stl_algobase.h:440
#4  0x0000000000468326 in std::copy<unsigned int*, unsigned int*> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0) at /usr/include/c++/5/bits/stl_algobase.h:472
#5  0x0000000000467d9e in std::__uninitialized_copy<true>::__uninit_copy<unsigned int*, unsigned int*> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0)
    at /usr/include/c++/5/bits/stl_uninitialized.h:93
#6  0x00000000004672de in std::uninitialized_copy<unsigned int*, unsigned int*> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0) at /usr/include/c++/5/bits/stl_uninitialized.h:126
#7  0x0000000000466621 in std::__uninitialized_copy_a<unsigned int*, unsigned int*, unsigned int> (__first=0x7ffff7fee004, __last=0x7ffff7fef004, __result=0x7fffdc0008e0)
    at /usr/include/c++/5/bits/stl_uninitialized.h:281
#8  0x000000000046515b in std::vector<unsigned int, std::allocator<unsigned int> >::_M_range_insert<unsigned int*> (this=0x7fffef7fd280, __position=<error reading variable: Cannot access memory at address 0x0>, 
    __first=0x7ffff7fee004, __last=0x7ffff7fef004) at /usr/include/c++/5/bits/vector.tcc:667
#9  0x0000000000464473 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_insert_dispatch<unsigned int*> (this=0x7fffef7fd280, __pos=<error reading variable: Cannot access memory at address 0x0>, 
    __first=0x7ffff7fee004, __last=0x7ffff7fef004) at /usr/include/c++/5/bits/stl_vector.h:1377
#10 0x0000000000463934 in std::vector<unsigned int, std::allocator<unsigned int> >::insert<unsigned int*, void> (this=0x7fffef7fd280, __position=<error reading variable: Cannot access memory at address 0x0>, 
    __first=0x7ffff7fee004, __last=0x7ffff7fef004) at /usr/include/c++/5/bits/stl_vector.h:1099
#11 0x00000000004623bc in BuffersStorage::getBufferRefs (this=0x6bea60, startDirectory=15872, size=4194304, refs=std::vector of length 0, capacity 0)
    at /home/xen/hostfs/projects/andr2000/drm_be/src/BuffersStorage.cpp:243
#12 0x0000000000460dbb in BuffersStorage::createDisplayBuffer (this=0x6bea60, dbCookie=1, startDirectory=15872, size=4194304, width=1024, height=1024, bpp=32)
    at /home/xen/hostfs/projects/andr2000/drm_be/src/BuffersStorage.cpp:73
#13 0x00000000004696d4 in CommandHandler::createDisplayBuffer (this=0x7fffe80010e8, req=...) at /home/xen/hostfs/projects/andr2000/drm_be/src/CommandHandler.cpp:152
#14 0x0000000000468fba in CommandHandler::processCommand (this=0x7fffe80010e8, req=...) at /home/xen/hostfs/projects/andr2000/drm_be/src/CommandHandler.cpp:99
#15 0x000000000046ce15 in ConCtrlRingBuffer::processRequest (this=0x7fffe8000fc0, req=...) at /home/xen/hostfs/projects/andr2000/drm_be/src/DisplayBackend.cpp:100
#16 0x00000000004728ca in XenBackend::RingBufferInBase<xen_displif_back_ring, xen_displif_sring, xendispl_req, xendispl_resp>::onReceiveIndication (this=0x7fffe8000fc0)
    at /usr/local/include/xen/be/RingBufferBase.hpp:229
#17 0x00007ffff7bb414f in XenBackend::RingBufferBase::<lambda()>::operator()(void) const (__closure=0x7fffe8000fd0) at /home/xen/al1hostfs/libxenbe/src/RingBufferBase.cpp:35
#18 0x00007ffff7bb498c in std::_Function_handler<void(), XenBackend::RingBufferBase::RingBufferBase(int, int, int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/5/functional:1871
#19 0x000000000047c834 in std::function<void ()>::operator()() const (this=0x7fffe8000fd0) at /usr/include/c++/5/functional:2267
#20 0x00007ffff7bb9e03 in XenBackend::XenEvtchn::eventThread (this=0x7fffe8000fc8) at /home/xen/al1hostfs/libxenbe/src/XenEvtchn.cpp:146
#21 0x00007ffff7bbbff9 in std::_Mem_fn_base<void (XenBackend::XenEvtchn::*)(), true>::operator()<, void>(XenBackend::XenEvtchn*) const (this=0x7fffe8000f40, __object=0x7fffe8000fc8)
    at /usr/include/c++/5/functional:600
#22 0x00007ffff7bbbf8d in std::_Bind_simple<std::_Mem_fn<void (XenBackend::XenEvtchn::*)()> (XenBackend::XenEvtchn*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7fffe8000f38)
    at /usr/include/c++/5/functional:1531
#23 0x00007ffff7bbbe94 in std::_Bind_simple<std::_Mem_fn<void (XenBackend::XenEvtchn::*)()> (XenBackend::XenEvtchn*)>::operator()() (this=0x7fffe8000f38) at /usr/include/c++/5/functional:1520
#24 0x00007ffff7bbbe24 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (XenBackend::XenEvtchn::*)()> (XenBackend::XenEvtchn*)> >::_M_run() (this=0x7fffe8000f20) at /usr/include/c++/5/thread:115
#25 0x00007ffff6c20c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007ffff6ef170a in start_thread (arg=0x7fffef7fe700) at pthread_create.c:333
#27 0x00007ffff638682d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by al1img** [comment]
Outdated
